### PR TITLE
New plotting function

### PR DESCRIPTION
**Pull request by TS404**

### CODE REVIEW

**Comment by TS404** [comment]
I've updated plot_domain with `GPI `anchor potting as yellow circles.
image

**Comment by TS404** [comment]
plot_domain function now shows Nglc sites and signal peptides. Can't yet seem to add the relevant info to the legend. Will have to remind myself about that part of ggplot2!

image

**Comment by missuse** [comment]
I have added the `scan_nglc` function to the package. I prefer `scan` to `predict` since no prediction is actually done, but rather the sequences are scanned for a motif. Since the occurrence of this motif was high I've added an (optional) argument (on by default) which checks the local hydrophilicity around the matched motif and if it is above a certain threshold then the found motif is `TRUE`. 

Thank you for the suggestion and initial code.

**Comment by TS404** [comment]
Good point. It's far more similar to scan_ag then it is to predict_hyp!

**Comment by TS404** [comment]
New basic analysis and plotting function to cluster sequences by their similarity of inter-proline distances
image

**Pull request closed without merging**
